// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// FileService is an autogenerated mock type for the FileService type
type FileService struct {
	mock.Mock
}

// Upload provides a mock function with given fields: src, contentType
func (_m *FileService) Upload(src io.Reader, contentType string) (string, error) {
	ret := _m.Called(src, contentType)

	var r0 string
	if rf, ok := ret.Get(0).(func(io.Reader, string) string); ok {
		r0 = rf(src, contentType)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(io.Reader, string) error); ok {
		r1 = rf(src, contentType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
