// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package integration

import (
	"goboilerplate/pkg/grpcapp"
	"goboilerplate/pkg/grpcapp/server"
	"goboilerplate/pkg/service/postservice"
	"goboilerplate/pkg/service/postservice/mocks"
	"goboilerplate/pkg/storage"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeGRPCApp(DB *gorm.DB, us *mocks.UuidService) (*grpcapp.App, error) {
	postRepo := storage.NewPostRepo(DB)
	postService := postservice.NewPostService(postRepo, us)
	postsServiceServer := server.NewPostsServer(postService)
	app := grpcapp.Initialize(postsServiceServer)
	return app, nil
}
