// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreatePostInput struct {
	Content  string  `json:"content"`
	Metadata *string `json:"metadata"`
}

type UpdatePostInput struct {
	Content  string  `json:"content"`
	Metadata *string `json:"metadata"`
}
